name: laiwand-env3
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - streamlit
    - azure-cognitiveservices-vision-computervision
    - pandas
    - numpy
    - matplotlib
    - watchdog
    - openai
    - plotly
    - scipy
    - pandasql
